---
- name: test pulling a per-device password from Cyberarm AIM
  hosts: cat_upgrade
  gather_facts: false
  vars:
    ca_base_url: "https://MyPath.com:12345"

  tasks:
  - name: credential retrieval basic
    cyberark.pas.cyberark_credential:
      api_base_url: "{{ ca_base_url }}"
      app_id: "testappid"
      query: "Safe=test;Object={{ inventory_hostname }}"
      validate_certs: no
      client_cert: /var/lib/awx/projects/general/client.crt
      client_key: /var/lib/awx/projects/general/client.pem
    register: ca_password
    no_log: true

#  - name: show cred retrieval
#    debug:
#      msg: "{{ ca_password.result.Content }}"

  - name: set ansible_password for each host
    set_fact:
      ansible_user: admin
# set based on result from above
      ansible_password: "{{ ca_password.result.Content }}"
    no_log: true

  - name: show ver
    ios_command:
      commands:
        - show ver

#  - name: show ver
#    debug:
#      msg: "{{ ansible_password }}"
